# Generated by Django 2.2.10 on 2020-02-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20200210_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='has_image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='img',
        ),
    ]
