# Generated by Django 2.2.10 on 2020-02-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('C++', 'C++'), ('C', 'C')], default='C++', max_length=5, verbose_name='Category'),
        ),
    ]
