# Generated by Django 2.2.10 on 2020-02-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20200213_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=models.CharField(max_length=700, verbose_name='Question statement'),
        ),
    ]
