# Generated by Django 2.2.10 on 2020-02-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answers',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='questions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
